# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import vehiculos_pb2 as vehiculos__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in vehiculos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VehiculosServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ActualizarVehiculo = channel.stream_unary(
                '/vehiculos.VehiculosService/ActualizarVehiculo',
                request_serializer=vehiculos__pb2.DatosJson.SerializeToString,
                response_deserializer=vehiculos__pb2.Respuesta.FromString,
                _registered_method=True)
        self.ObtenerEstadoVehiculos = channel.unary_unary(
                '/vehiculos.VehiculosService/ObtenerEstadoVehiculos',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=vehiculos__pb2.EstadoVehiculos.FromString,
                _registered_method=True)


class VehiculosServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ActualizarVehiculo(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerEstadoVehiculos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VehiculosServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ActualizarVehiculo': grpc.stream_unary_rpc_method_handler(
                    servicer.ActualizarVehiculo,
                    request_deserializer=vehiculos__pb2.DatosJson.FromString,
                    response_serializer=vehiculos__pb2.Respuesta.SerializeToString,
            ),
            'ObtenerEstadoVehiculos': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerEstadoVehiculos,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=vehiculos__pb2.EstadoVehiculos.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vehiculos.VehiculosService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vehiculos.VehiculosService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VehiculosService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ActualizarVehiculo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/vehiculos.VehiculosService/ActualizarVehiculo',
            vehiculos__pb2.DatosJson.SerializeToString,
            vehiculos__pb2.Respuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerEstadoVehiculos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vehiculos.VehiculosService/ObtenerEstadoVehiculos',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            vehiculos__pb2.EstadoVehiculos.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
